[program:sam_watchdog]
environment=PROC_NAME="%(program_name)s",STALL_MIN="45"
command=/opt/supervisor-scripts/sam_watchdog.sh
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
